name: Release Posts
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: 0 8 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: $